name = "vkrama-store"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"
vars = { NODE_VERSION = "22" }

[[d1_databases]]
binding = "DB"
database_name = "vkrama-db"
database_id = "b8665214-d54a-41e3-a392-ea536c4d1188"

[[r2_buckets]]
binding = "R2_STORE"
bucket_name = "vkrama-assets"

[[kv_namespaces]]
binding = "CACHE"
id = "b5cb9dd451db4a6fb595fed867a8f3a7"

[[vectorize]]
binding = "VECTORIZE"
index_name = "vkrama-products"

[[durable_objects.bindings]]
name = "CART_DO"
class_name = "CartDO"
script_name = "vkrama-services"

[[durable_objects.bindings]]
name = "INVENTORY_DO"
class_name = "InventoryDO"
script_name = "vkrama-services"

[[durable_objects.bindings]]
name = "NOTIFICATION_DO"
class_name = "NotificationDO"
script_name = "vkrama-services"

[[queues.producers]]
queue = "vkrama-order-processor"
binding = "ORDER_QUEUE"

[[queues.producers]]
queue = "vkrama-email"
binding = "EMAIL_QUEUE"

[[queues.producers]]
queue = "vkrama-analytics"
binding = "ANALYTICS_QUEUE"

[ai]
binding = "AI"
